# Auto-generated by Babel (Do not modify)
from dropbox import arg_struct_parser as asp

# We use an identity function because we don't need to mutate the return value
# of the parser in any way.
def identity(x):
    return x

users_quota_info_validator = asp.Record(
    # The user's total quota allocation (bytes).
    ('quota', asp.Nat()),
    # The user's used quota outside of shared folders (bytes).
    ('normal', asp.Nat()),
    # The user's used quota in shared folders (bytes).
    ('shared', asp.Nat()),
    # The user's used quota in datastores (bytes).
    ('datastores', asp.Nullable(asp.Nat())),
)

users_team_validator = asp.Record(
    # The team's unique ID.
    ('id', asp.StringB()),
    # The name of the team.
    ('name', asp.StringB()),
)

users_account_info_validator = asp.Record(
    # The full name of a user.
    ('display_name', asp.StringB()),
    # The user's unique Dropbox ID.
    ('account_id', asp.StringB()),
    # The user's e-mail address.
    ('email', asp.StringB()),
    # The user's two-letter country code, if available.
    ('country', asp.StringB(regex='[US]+', min_length=2, max_length=2)),
    # The user's :link:`referral link https://www.dropbox.com/referrals`.
    ('referral_link', asp.StringB()),
    # The user's quota.
    ('quota', users_quota_info_validator),
    # Whether the user has a personal and business account.
    ('is_paired', asp.Boolean()),
    # If this account is a member of a team.
    ('team', users_team_validator),
)

users_more_account_info_validator = asp.Record(
    # Locale set by the user.
    ('locale', asp.StringB()),
)

users_account_info_request_validator = asp.Record(
    # A user's account identifier. Use "me" to get information for the current
    # account.
    ('account_id', asp.Nullable(asp.StringB()), 'me'),
)

